import {
  collectNativeTokens,
  formatNumber,
  type Dictionary,
  type Rgba,
  type ColorToken,
  type NumberToken
} from './native-tokens.ts'

const toHexByte = (channel: number): string =>
  Math.round(channel * 255)
    .toString(16)
    .toUpperCase()
    .padStart(2, '0')

const kotlinColor = ({ red, green, blue, alpha }: Rgba): string =>
  `Color(0x${toHexByte(alpha)}${toHexByte(red)}${toHexByte(green)}${toHexByte(blue)})`

const section = (title: string, lines: string[]): string[] => {
  if (lines.length === 0) return []
  return [`    // ${title}`, ...lines]
}

const formatter = (dictionary: Dictionary): string => {
  const tokens = collectNativeTokens(dictionary)

  const sections = [
    section(
      'Colors',
      tokens.colors.map(
        ({ name, color }) => `    val ${name} = ${kotlinColor(color)}`
      )
    ),
    section(
      'Font sizes (sp)',
      tokens.fontSizes.map(
        ({ name, value }) => `    val ${name} = ${formatNumber(value)}.sp`
      )
    ),
    section(
      'Line heights (multipliers)',
      tokens.lineHeights.map(
        ({ name, value }) => `    const val ${name} = ${formatNumber(value)}f`
      )
    ),
    section(
      'Radii (dp)',
      tokens.radii.map(
        ({ name, value }) => `    val ${name} = ${formatNumber(value)}.dp`
      )
    ),
    section(
      'Spacing (dp)',
      tokens.space.map(
        ({ name, value }) => `    val ${name} = ${formatNumber(value)}.dp`
      )
    )
  ].filter((lines) => lines.length > 0)

  const body = sections.map((lines) => lines.join('\n')).join('\n\n')

  return `// Do not edit directly — generated by @atom-learning/theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object ThemeTokens {
${body}
}
`
}

formatter.nested = true

export default formatter
export { setBuildConfig } from './shared.ts'
