import {
  collectNativeTokens,
  formatNumber,
  type Dictionary,
  type Rgba,
  type ColorToken,
  type NumberToken
} from './native-tokens.ts'

const swiftColor = ({ red, green, blue, alpha }: Rgba): string =>
  `Color(red: ${formatNumber(red)}, green: ${formatNumber(green)}, blue: ${formatNumber(blue)}, opacity: ${formatNumber(alpha)})`

const colorSection = (title: string, tokens: ColorToken[]): string[] => {
  if (tokens.length === 0) return []
  return [
    `    // MARK: - ${title}`,
    '',
    ...tokens.map(
      ({ name, color }) => `    public static let ${name} = ${swiftColor(color)}`
    )
  ]
}

const numberSection = (title: string, tokens: NumberToken[]): string[] => {
  if (tokens.length === 0) return []
  return [
    `    // MARK: - ${title}`,
    '',
    ...tokens.map(
      ({ name, value }) =>
        `    public static let ${name}: CGFloat = ${formatNumber(value)}`
    )
  ]
}

const formatter = (dictionary: Dictionary): string => {
  const tokens = collectNativeTokens(dictionary)

  const sections = [
    colorSection('Colors', tokens.colors),
    numberSection('Font sizes (pt)', tokens.fontSizes),
    numberSection('Line heights (multipliers)', tokens.lineHeights),
    numberSection('Radii (pt)', tokens.radii),
    numberSection('Spacing (pt)', tokens.space)
  ].filter((section) => section.length > 0)

  const body = sections.map((section) => section.join('\n')).join('\n\n')

  return `// Do not edit directly — generated by @atom-learning/theme

import SwiftUI

public enum ThemeTokens {
${body}
}
`
}

formatter.nested = true

export default formatter
export { setBuildConfig } from './shared.ts'
